@startuml
'DB Diagram
skinparam class{
    BackgroundColor LightGreen
}

skinparam object{
    BackgroundColor Cyan
}

skinparam json{
    BackgroundColor LightGreen
}

object recipe {
    * id INT
    meal_type CHAR
    recipe_name TEXT
    base64_image TEXT
    ingredients ingredient[]
    macros recipe_macros
}

class ingredient <<(C,plum)>>{
    name TEXT
    grams INT
    calories INT
    fats FLOAT
    carbohydrates FLOAT
    protein FLOAT
    multiplier FLOAT
    base64_image TEXT
}

class recipe_macros <<(C,plum)>>{
    total_calories FLOAT
    total_fats FLOAT
    total_carbs FLOAT
    total_protein FLOAT
}

recipe::ingredient ||--|{ ingredient
recipe::macros --|| recipe_macros

object recipe_instructions{
    * id INT
    instructions JSON
    recipe_id CONSTRAINT FOREIGN KEY INT
}

object ingredients{
    * id INT
    name TEXT
    calories FLOAT
    fats FLOAT
    carbohydrates FLOAT
    protein FLOAT
    base64_image TEXT
}

json Instructions{
    "name":"Amatriciana",
    "steps": [
    {
        "step_number":1,
        "instruction": "Start by..."
    },
    {
        "step_number":2,
        "instruction": "Then, start with the..."
    },
    {
        "...":"..."
    }
    ],
    
    "notes": [
    {
        "note_number":1,
        "note_text": "By the way..."
    },
    {
        "note_number":2,
        "note_text": "Remember to..."
    },
    {
        "...":"..."
    }
    ]
}

recipe_instructions::recipe_id -> recipe::id
Instructions -> recipe_instructions::instructions

@enduml

@startuml

if (counter) equals (7) then
:Print the weekly macros;
else
:;

@enduml



@startuml
skinparameters
@enduml

'PlanMeals
@startuml
class DailyMeal{
    List<Recipes>
    TotalDailyMacros
}

class WeeklyMeals{
    List<DailyMeal> [7]
    TotalWeeklyMacros
}

DailyMeal --> WeeklyMeals
@enduml