@startuml
'DB Diagram
skinparam class{
    BackgroundColor LightGreen
}

skinparam object{
    BackgroundColor Cyan
}

skinparam json{
    BackgroundColor Orange
}

object recipe {
    * id SERIAL PRIMARY KEY
    meal_type CHAR
    recipe_name TEXT
    base64_image TEXT
    ingredients ingredient[]
    macros recipe_macros
}

class ingredient <<(C,plum)>>{
    name TEXT
    grams INT
    calories INT
    fats FLOAT
    carbohydrates FLOAT
    protein FLOAT
    multiplier FLOAT
    base64_image TEXT
}

class recipe_macros <<(C,plum)>>{
    total_calories FLOAT
    total_fats FLOAT
    total_carbs FLOAT
    total_protein FLOAT
}

recipe::ingredient ||--|{ ingredient
recipe::macros --|| recipe_macros

object recipe_instructions{
    id SERIAL PRIMARY KEY
    instructions JSON
    recipe_id CONSTRAINT FOREIGN KEY INT
}

json Instructions{
    "name":"Amatriciana",
    "1":"Start by...",
    "2":"Then, start with the...",
    "...":"...",
    "note1":"By the way...",
    "note2":"Remember to...",
    "...":"..."
}

recipe_instructions::recipe_id -> recipe::id
Instructions -> recipe_instructions::instructions

@enduml

@startuml

if (counter) equals (7) then
:Print the weekly macros;
else
:;

@enduml



@startuml
skinparameters
@enduml

'PlanMeals
@startuml
class DailyMeal{
    List<Recipes>
    TotalDailyMacros
}

class WeeklyMeals{
    List<DailyMeal> [7]
    TotalWeeklyMacros
}

DailyMeal --> WeeklyMeals
@enduml