@startuml
'Class Diagram
class recipe{
    uint recipe_number
    char meal_type
    string recipe_name
    string image_str
    ingredient[] ingredients
    total_macros macros
}

class ingredient{
    string name
    float kg
    float calories
    float fats
    float carbohydrates
    float protein
    float multiplier
}

class macros{
    float total_calories
    float total_fats
    float total_carbs
    float total_protein
}

ingredient --|{ recipe::ingredients
macros --> recipe::macros
@enduml

@startuml
'DB Diagram
entity Recipe {
    * id INT
    meal_type CHAR
    recipe_name TEXT
    image_path TEXT
    ingredients Ingredient[]
    macros recipe_macros
}

class Ingredient {
    name TEXT
    grams INT
    calories INT
    fats FLOAT
    carbohydrates FLOAT
    protein FLOAT
    multiplier FLOAT
}

class recipe_macros {
    total_calories FLOAT
    total_fats FLOAT
    total_carbs FLOAT
    total_protein FLOAT
}

Recipe::ingredient ||--|{ Ingredient
Recipe::macros --|| recipe_macros
@enduml

@startuml

if (counter) equals (7) then
:Print the weekly macros;
else
:;

@enduml



@startuml
skinparameters
@enduml

'PlanMeals
@startuml
class DailyMeal{
    List<Recipes>
    TotalDailyMacros
}

class WeeklyMeals{
    List<DailyMeal> [7]
    TotalWeeklyMacros
}

DailyMeal --> WeeklyMeals
@enduml