@startuml
skinparam class{
    BackgroundColor LightGreen
}

skinparam object{
    BackgroundColor Cyan
}

skinparam json{
    BackgroundColor LightGreen
}

object recipe {
    * id INT
    meal_type CHAR
    recipe_name TEXT
    base64_image TEXT
    ingredients ingredient[]
    total_cost FLOAT
    macros recipe_macros
}

class ingredient <<(C,plum)>>{
    name TEXT
    grams INT
    calories INT
    fats FLOAT
    carbohydrates FLOAT
    protein FLOAT
    cost_per_100g FLOAT
    multiplier FLOAT
    base64_image TEXT
}

class recipe_macros <<(C,plum)>>{
    total_calories FLOAT
    total_fats FLOAT
    total_carbs FLOAT
    total_protein FLOAT
}

recipe::ingredient ||--|{ ingredient
recipe::macros --|| recipe_macros

object recipe_instructions{
    * id INT
    instructions JSON
    recipe_id CONSTRAINT FOREIGN KEY INT
}

object ingredients{
    * id INT
    name TEXT
    calories FLOAT
    fats FLOAT
    carbohydrates FLOAT
    protein FLOAT
    base64_image TEXT
}

object sought_after_items{
    * id INT
    name TEXT
    base64_image TEXT
    type TEXT
    price FLOAT
}

json Instructions{
    "name":"Amatriciana",
    "steps": [
    {
        "step_number":1,
        "instruction": "Start by..."
    },
    {
        "step_number":2,
        "instruction": "Then, start with the..."
    },
    {
        "...":"..."
    }
    ],
    
    "notes": [
    {
        "note_number":1,
        "note_text": "By the way..."
    },
    {
        "note_number":2,
        "note_text": "Remember to..."
    },
    {
        "...":"..."
    }
    ]
}

recipe_instructions::recipe_id -> recipe::id
Instructions -> recipe_instructions::instructions

ingredient::name <- ingredients::name
ingredient::calories <- ingredients::calories
ingredient::fats <- ingredients::fats
ingredient::carbohydrates <- ingredients::carbohydrates
ingredient::protein <- ingredients::protein
ingredient::base64_image <- ingredients::base64_image
@enduml

@startuml
skinparameters
@enduml